// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TrashCollectionAPI.Data.Contexts;

#nullable disable

namespace TrashCollectionAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240625005255_Initialmigration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrashCollectionAPI.Models.CaminhaoModel", b =>
                {
                    b.Property<int>("IdCaminhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaminhao"));

                    b.Property<int>("HNumeroMaxCapacidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdStatus")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdCaminhao");

                    b.HasIndex("IdStatus");

                    b.ToTable("Caminhao", (string)null);
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.ColetaModel", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<double>("NumeroVolume")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdColeta");

                    b.ToTable("Coleta", (string)null);
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.RotaModel", b =>
                {
                    b.Property<int>("IdRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRota"));

                    b.Property<string>("DescricaoRota")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdColeta")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRota");

                    b.HasIndex("IdColeta");

                    b.ToTable("Rota", (string)null);
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.StatusModel", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.HasKey("IdStatus");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.CaminhaoModel", b =>
                {
                    b.HasOne("TrashCollectionAPI.Models.StatusModel", "Status")
                        .WithMany("Caminhoes")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.RotaModel", b =>
                {
                    b.HasOne("TrashCollectionAPI.Models.ColetaModel", "Coleta")
                        .WithMany("Rotas")
                        .HasForeignKey("IdColeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coleta");
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.ColetaModel", b =>
                {
                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("TrashCollectionAPI.Models.StatusModel", b =>
                {
                    b.Navigation("Caminhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
